/* tslint:disable */
/* eslint-disable */
/**
 * Ebb Application API
 * API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationQueryDto
 */
export interface PaginationQueryDto {
    /**
     * 
     * @type {number}
     * @memberof PaginationQueryDto
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationQueryDto
     */
    'limit'?: number;
}

