/* tslint:disable */
/* eslint-disable */
/**
 * Ebb Application API
 * API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskDto
 */
export interface TaskDto {
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {boolean}
     * @memberof TaskDto
     */
    'archived': boolean;
}

