/* tslint:disable */
/* eslint-disable */
/**
 * Ebb Application API
 * API description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateTaskDto
 */
export interface UpdateTaskDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'content'?: string;
}

